# Generated by Django 5.1 on 2024-08-26 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProblem',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProblem',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('model_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('manufacturer', models.ManyToManyField(to='problems.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='MDR',
            fields=[
                ('mdr_report_key', models.IntegerField(primary_key=True, serialize=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.device')),
                ('device_problem', models.ManyToManyField(to='problems.deviceproblem')),
                ('patient_problem', models.ManyToManyField(to='problems.patientproblem')),
            ],
        ),
    ]
