# Generated by Django 5.1 on 2024-08-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdr',
            name='event_date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
