# Generated by Django 5.1 on 2024-09-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_mdr_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdr',
            name='event_type',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
